"""Add user.last_visit column to track visit streak

Revision ID: 05edf6024491
Revises: 50a9c934be46
Create Date: 2024-03-08 12:31:52.932860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05edf6024491'
down_revision = '50a9c934be46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'high_scores', ['id'])
    op.create_unique_constraint(None, 'study_sets', ['id'])
    op.create_unique_constraint(None, 'studyset_questions', ['id'])
    op.add_column('users', sa.Column('visit_streak', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_visit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_visit')
    op.drop_column('users', 'visit_streak')
    op.drop_constraint(None, 'studyset_questions', type_='unique')
    op.drop_constraint(None, 'study_sets', type_='unique')
    op.drop_constraint(None, 'high_scores', type_='unique')
    # ### end Alembic commands ###
