"""track user visit streak

Revision ID: 122576e48179
Revises: 05edf6024491
Create Date: 2024-03-08 13:32:14.759080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122576e48179'
down_revision = '05edf6024491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_visit',
               existing_type=sa.INTEGER(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_visit',
               existing_type=sa.Date(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
